name: go deploy
on:
  push:
    branches:
      - main
    paths:
      - "packages/go/**"
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get Go dependencies
        working-directory: packages/go
        run: go mod download

      - name: Get npm dependencies
        working-directory: packages/go
        run: |
          npm install -g @serverless-devs/s
          s config add --AccessKeyID ${{ secrets.ALIYUNACCESSKEYID }} --AccessKeySecret ${{ secrets.ALIYUNACCESSKEYSECRET }}

      - name: Deploy
        working-directory: packages/go/cmd/server
        env:
          endpoint: ${{ secrets.ALIYUNOSSMOUNTENDPOINT }}
          bucketName: ${{ secrets.ALIYUNOSSMOUNTBUCKETNAME }}
          bucketPath: ${{ secrets.ALIYUNOSSMOUNTBUCKETPATH }}
          mountDir: ${{ secrets.ALIYUNOSSMOUNTMOUNTDIR }}
        run: |
          s deploy -y --use-local
