name: go deploy
on:
  push:
    paths:
      - "packages/go/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get Go dependencies
        working-directory: packages/go
        run: go mod download

      - name: Get npm dependencies
        working-directory: packages/go
        run: |
          npm install -g @serverless-devs/s
          s config add --AccessKeyID ${{ secrets.ALIYUNACCESSKEYID }} --AccessKeySecret ${{ secrets.ALIYUNACCESSKEYSECRET }}

      - name: Deploy
        working-directory: packages/go/cmd/server
        run: |
          s deploy
